name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run Tests
        run: |
          cd tests
          cd Timezone.Management.Application.Tests    
          dotnet test

  pushImageToDockerHub:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    outputs:
      image: ${{ steps.image_tag.outputs.full }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get current datetime
        id: datetime
        run: echo "now=$(TZ='America/Sao_Paulo' date +'%Y-%m-%d--%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Set full image tag
        id: image_tag
        run: echo "full=${{ vars.DOCKERHUB_USERNAME}}/timezone-management-api:${{ steps.datetime.outputs.now }}" >> $GITHUB_OUTPUT
      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ steps.image_tag.outputs.full }}

  terraformPlan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: pushImageToDockerHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.3"

      - name: Validate resources
        run: |
          cd infrastructure
          terraform fmt -check -recursive
          terraform init
          terraform validate

      - name: Terraform plan
        run: |
          cd infrastructure
          terraform plan \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="container_image=${{ needs.pushImageToDockerHub.outputs.image }}" \
            -var="db_login=${{ secrets.DB_LOGIN }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v7
        with:
          name: tfplan
          path: infrastructure/tfplan

  terraformApply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraformPlan
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.3"

      - name: Terraform init
        run: |
          cd infrastructure
          terraform init

      - name: Download plan artifact
        uses: actions/download-artifact@v7
        with:
          name: tfplan
          path: infrastructure/

      - name: Apply resources
        run: |
          cd infrastructure
          terraform apply -auto-approve tfplan
          
  deploy:
    name: Deploy
    needs: [terraformApply, pushImageToDockerHub]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Log in to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ needs.pushImageToDockerHub.outputs.image }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
